language: php

php:
  - 7.1
  - 7.2

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

install:
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - composer validate --strict && vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit --coverage-text